resolver: lts-14.21

ghc-options: {"$locals": -ddump-to-file -ddump-hi}

extra-deps:
  - streaming-events-1.0.1
  - github: kadena-io/chainweb-api
    commit: 07a515e9b5401b73ff59af55b369590273decce7
