resolver: lts-14.27

ghc-options: {"$locals": -ddump-to-file -ddump-hi}

extra-deps:
  - streaming-events-1.0.1
  - strict-tuple-0.1.3
  - witherable-class-0
  - github: kadena-io/chainweb-api
    commit: e90509233e7073e99871c94b19c88e98ed18cd78
  - github: tathougies/beam
    commit: 2fa99310557e49b37a59e349032ff7236085b6f8
    subdirs:
      - beam-core
      - beam-migrate
      - beam-postgres
