resolver: lts-14.27

ghc-options: {"$locals": -ddump-to-file -ddump-hi}

extra-deps:
  - streaming-events-1.0.1
  - strict-tuple-0.1.3
  - github: kadena-io/chainweb-api
    commit: 0792df840e49821f60a8e6e5a1cdc6c5862137a1
  - github: tathougies/beam
    commit: 2fa99310557e49b37a59e349032ff7236085b6f8
    subdirs:
      - beam-core
      - beam-migrate
      - beam-postgres
