resolver: lts-14.25

ghc-options: {"$locals": -ddump-to-file -ddump-hi}

extra-deps:
  - streaming-events-1.0.1
  - github: kadena-io/chainweb-api
    commit: 2f54cae4c029bcdb3a7f09b5dd766cc365e14c34
  - github: tathougies/beam
    commit: 2b704ee1fe55ff3a6851697040123a86540f485e
    subdirs:
      - beam-core
      - beam-migrate
      - beam-postgres
